routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Frontend.dashboard.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/login', 'Auth\Logincontroller@showLogin')->name('auth.login');
Route::get('/register', 'Auth\RegisterController@showRegister')->name('auth.register');
Route::post('/processRegister', 'Auth\RegisterController@processRegister')->name('auth.processRegister');


Route::group(['as' => 'dashboard.', 'prefix' => 'dashboard', 'namespace' => 'Frontend'], function () {

    Route::get('/', 'DashboardController@Index')->name('dashboard');
    Route::get('/ads', 'DashboardController@Ads')->name('ads');
    Route::get('/pricing', 'DashboardController@Pricing')->name('pricing');
    Route::get('/contact', 'DashboardController@Contact')->name('contact');
    Route::get('/about_us', 'DashboardController@AboutUs')->name('about_us');
    Route::get('/product/{id}', 'DashboardController@product')->name('product');

});


Route::group(['as' => 'search.', 'prefix' => 'search', 'namespace' => 'Frontend'], function () {

	Route::post('/search', 'SerachController@Search')->name('search');

});

Route::group(['as' => 'checkout.', 'prefix' => 'checkout', 'namespace' => 'Frontend'], function () {
	
	Route::get('/checkout', 'OrderController@ShowForm')->name('checkout');

});

app/Http/Controllers/Frontend/DashboardController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Db;

class DashboardController extends Controller
{
    public function Index()
    {
        $categories = DB::table('shop_categories')->get();
        $product    = DB::table('products')->get();
    	return view('Frontend.dashboard.home', ['product' => $product, 'category' => $categories]);
    }


    public function Ads()
    {
        $categories = DB::table('shop_categories')->get();
        $product    = DB::table('products')->get();
        $shop = DB::table('shops')->get();

    	return view('Frontend.dashboard.ads', ['shops' => $shop, 'product' => $product, 'category' => $categories]);
    }


    public function Contact()
    {
    	return view('Frontend.dashboard.contact');
    }


    public function Pricing()
    {
    	return view('Frontend.dashboard.pricing');
    }


    public function AboutUs()
    {
    	return view('Frontend.dashboard.about_us');
    }

    public function product($id){

        $product = DB::table('products')->where('id', $id)->first();
        $catrgories = DB::table('shop_categories')->get();

        return view('Frontend.dashboard.product', ['product' => $product, 'category' => $catrgories]);
    }
}

app/Http/Controllers/Frontend/OrderController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    public function ShowForm(){
    	return view('Frontend.dashboard.checkout');
    }
}

app/Http/Controllers/Frontend/SerachController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;

class SerachController extends Controller
{
    public function Search()
    {
    	$keyword = request()->keyword;

    	$tags = DB::table('product_tags')
    			->select('id')
    			->where('tag_name', 'like', '%'.$keyword.'%')
    			->orWhere('slug', 'like', '%'.$keyword.'%')
    			->first();

    	$product = DB::table('products')->select('*')
    				->where('tag_id', '=', $tags->id)
    				->orWhere('pro_name', 'like', "%".$keyword."%")
    				->orWhere('discount', 'like', "%".$keyword."%")
    				->get();

    	return response()->json(['success' => true, 'data' => $product]);
    }
}

resources/views/Frontend/partials/footer.blade.php
<footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-9">
            <div class="row">
              <div class="col-md-6">
                <h2 class="footer-heading mb-4 text-dark font-weight-bold">About</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident rerum unde possimus molestias
                  dolorem
                  fuga, illo quis fugiat!</p>
              </div>

              <div class="col-md-3">
                <h2 class="footer-heading mb-4 text-dark font-weight-bold">Navigations</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Services</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-md-3">
                <h2 class="footer-heading mb-4 text-dark font-weight-bold">Follow Us</h2>
                <a href="#" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
                <a href="#" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
                <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                <a href="#" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <form action="#" method="post">
              <div class="input-group mb-3 footer-input">
                <input type="text" class="form-control border-secondary text-white bg-transparent"
                  placeholder="Search products" aria-label="Enter Email" aria-describedby="button-addon2">
                <div class="input-group-append">
                  <button class="btn btn-warning text-white" type="button" id="button-addon2">Search</button>
                </div>
              </div>
            </form>
          </div>
        </div>

      </div>
  </div>
  </footer>

resources/views/Frontend/partials/header.blade.php
<header class="site-navbar container py-0 " role="banner">

      <!-- <div class="container"> -->
        <div class="row align-items-center">
          
          <div class="col-6 col-xl-2">
            <h1 class="mb-0 site-logo"><a href="{{ route('dashboard.dashboard') }}" class="mb-0">OfferBasket</a></h1>
          </div>
          <div class="col-12 col-md-10 d-none d-xl-block">
            <nav class="site-navigation position-relative text-right" role="navigation">

            <ul class="site-menu js-clone-nav mr-auto d-none d-lg-block">
              <li class="active"><a href="{{ route('dashboard.dashboard') }}">Home</a></li>
              <li><a href="{{ route('dashboard.ads') }}">Ads</a></li>
              <li><a href="{{ route('dashboard.pricing') }}">Pricing</a></li>
              <li><a href="{{ route('dashboard.contact') }}">Contact</a></li>
              <li class="has-children">
                <a href="#">About</a>
                <ul class="dropdown">
                  <li><a href="{{ route('dashboard.about_us') }}">The Company</a></li>
                  <li><a href="#">Careers</a></li>
                </ul>
              </li>

              <li class="has-children">
                <a href="#">Join</a>
                <ul class="dropdown">
                  <li><a href="{{ route('auth.login') }}">Login</a></li>
                  <li><a href="{{ route('auth.register') }}">Register</a></li>
                </ul>
              </li>
            </ul>

            </nav>
          </div>

          <div class="d-inline-block d-xl-none ml-auto py-3 col-6 text-right" style="position: relative; top: 3px;">
            <a href="#" class="site-menu-toggle js-menu-toggle text-white"><span class="icon-menu h3"></span></a>
          </div>

        </div>
      <!-- </div> -->
      
    </header>

resources/views/Frontend/partials/main.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>OfferBasket</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}" />

    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700,800" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('fonts/icomoon/style.css') }}">

    <link rel="stylesheet" href="{{ asset('/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/magnific-popup.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/jquery-ui.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/owl.theme.default.min.css') }}">

    <link rel="stylesheet" href="{{ asset('/css/bootstrap-datepicker.css') }}">

    <link rel="stylesheet" href="{{ asset('/fonts/flaticon/font/flaticon.css') }}">

    <link rel="stylesheet" href="{{ asset('/css/aos.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/rangeslider.css') }}">

    <link rel="stylesheet" href="{!! asset('/css/style.css') !!}">

    @yield('styles')
    
  </head>

<body>

    <div class="site-wrap">

        @include('Frontend.partials.header')

        @yield('content')

        @include('Frontend.partials.footer')

    </div>

    <script src="{{ asset('/js/jquery-3.3.1.min.js') }}"></script>
    <script>
        $.ajaxSetup({
        headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>
    <script src="{{ asset('/js/jquery-migrate-3.0.1.min.js') }}"></script>
    <script src="{{ asset('/js/jquery-ui.js') }}"></script>
    <script src="{{ asset('/js/popper.min.js') }}"></script>
    <script src="{{ asset('/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('/js/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('/js/jquery.stellar.min.js') }}"></script>
    <script src="{{ asset('/js/jquery.countdown.min.js') }}"></script>
    <script src="{{ asset('/js/jquery.magnific-popup.min.js') }}"></script>
    <script src="{{ asset('/js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('/js/aos.js') }}"></script>
    <script src="{{ asset('/js/rangeslider.min.js') }}"></script>

    

    @yield('scripts')

    <script src="{{ asset('/js/main.js') }}"></script>

</body>
</html>