routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Frontend.dashboard.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/login', 'Auth\Logincontroller@showLogin')->name('auth.login');
Route::get('/register', 'Auth\RegisterController@showRegister')->name('auth.register');
Route::post('/processRegister', 'Auth\RegisterController@processRegister')->name('auth.processRegister');


Route::group(['as' => 'dashboard.', 'prefix' => 'dashboard', 'namespace' => 'Frontend'], function () {

    Route::get('/', 'DashboardController@Index')->name('dashboard');
    Route::get('/ads', 'DashboardController@Ads')->name('ads');
    Route::get('/pricing', 'DashboardController@Pricing')->name('pricing');
    Route::get('/contact', 'DashboardController@Contact')->name('contact');
    Route::get('/about_us', 'DashboardController@AboutUs')->name('about_us');
    Route::get('/product/{id}', 'DashboardController@product')->name('product');

});


Route::group(['as' => 'search.', 'prefix' => 'search', 'namespace' => 'Frontend'], function () {

	Route::post('/search', 'SerachController@Search')->name('search');

});

Route::group(['as' => 'checkout.', 'prefix' => 'checkout', 'namespace' => 'Frontend'], function () {
	
	Route::get('/checkout', 'OrderController@ShowForm')->name('checkout');

});

app/Http/Controllers/Frontend/DashboardController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Db;

class DashboardController extends Controller
{
    public function Index()
    {
        $categories = DB::table('shop_categories')->get();
        $product    = DB::table('products')->get();
    	return view('Frontend.dashboard.home', ['product' => $product, 'category' => $categories]);
    }


    public function Ads()
    {
        $categories = DB::table('shop_categories')->get();
        $product    = DB::table('products')->get();
        $shop = DB::table('shops')->get();

    	return view('Frontend.dashboard.ads', ['shops' => $shop, 'product' => $product, 'category' => $categories]);
    }


    public function Contact()
    {
    	return view('Frontend.dashboard.contact');
    }


    public function Pricing()
    {
    	return view('Frontend.dashboard.pricing');
    }


    public function AboutUs()
    {
    	return view('Frontend.dashboard.about_us');
    }

    public function product($id){

        $product = DB::table('products')->where('id', $id)->first();
        $catrgories = DB::table('shop_categories')->get();

        return view('Frontend.dashboard.product', ['product' => $product, 'category' => $catrgories]);
    }
}

app/Http/Controllers/Frontend/OrderController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    public function ShowForm(){
    	return view('Frontend.dashboard.checkout');
    }
}

app/Http/Controllers/Frontend/SerachController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;

class SerachController extends Controller
{
    public function Search()
    {
    	$keyword = request()->keyword;

    	$tags = DB::table('product_tags')
    			->select('id')
    			->where('tag_name', 'like', '%'.$keyword.'%')
    			->orWhere('slug', 'like', '%'.$keyword.'%')
    			->first();

    	$product = DB::table('products')->select('*')
    				->where('tag_id', '=', $tags->id)
    				->orWhere('pro_name', 'like', "%".$keyword."%")
    				->orWhere('discount', 'like', "%".$keyword."%")
    				->get();

    	return response()->json(['success' => true, 'data' => $product]);
    }
}

resources/views/Frontend/dashboard/about_us.blade.php
@extends('Frontend.partials.main')

@section('content')

<div class="site-blocks-cover inner-page-cover overlay" style="background-image: url('/images/hero_2.jpg');" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">

      <div class="col-md-10" data-aos="fade-up" data-aos-delay="400">
        
        
        <div class="row justify-content-center mt-5">
          <div class="col-md-8 text-center">
            <h1>About Us</h1>
            <p class="mb-0">Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
          </div>
        </div>

        
      </div>
    </div>
  </div>
</div>  


<div class="site-section">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6">
        <img src="{{ asset('/images/hero_2.jpg') }}" alt="Image" class="img-fluid rounded">
      </div>
      <div class="col-md-5 ml-auto">
        <h2 class="text-dark mb-3">Why OfferBasket</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam voluptates a explicabo delectus sed labore dolor enim optio odio at!</p>
        <p class="mb-4">Adipisci dolore reprehenderit est et assumenda veritatis, ex voluptate odio consequuntur quo ipsa accusamus dicta laborum exercitationem aspernatur reiciendis perspiciatis!</p>

        <ul class="ul-check list-unstyled primary">
          <li>Adipisci dolore reprehenderit</li>
          <li>Accusamus dicta laborum</li>
          <li>Delectus sed labore</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="site-section"  data-aos="fade">
  <div class="container">
    
    
    <div class="row  mb-5">
      <div class="col-12">
        <img src="{{ asset('/images/img_2.jpg') }}" alt="Image" class="img-fluid mb-5">
      </div>
    </div>
    <div class="row mb-5">

      <div class="col-md-4 ml-auto whyus">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam eveniet laudantium dignissimos atque labore excepturi perspiciatis ut fugit eius itaque iste quibusdam dolore consectetur reprehenderit. Illum molestiae.</p>
        <p><a href="#" class="">Read More</a></p>
      </div>
      <div class="col-md-4 whyus">
        <p>Similique neque facere cum! Et esse natus qui fugiat temporibus voluptate debitis similique eos illum pariatur suscipit placeat omnis perferendis ab enim quis eligendi minima explicabo aperiam. Eaque minus itaque?</p>
        <p><a href="#" class="">Read More</a></p>
      </div>
    </div>

    <div class="row mb-5 mt-5">
      <div class="col-md-4 text-left border-primary">
        <h2 class="font-weight-light text-dark pb-3">Our Team</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
        <img src="{{ asset('images/person_1.jpg') }}" alt="Image" class="img-fluid mb-3">
        <h3 class="h4">Susan Horton</h3>
        <p class="caption mb-3 text-primary">Founder</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum facilis, sint libero commodi tenetur ducimus accusantium inventore.</p>
      </div>
      <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
        <img src="{{ asset('images/person_2.jpg') }}" alt="Image" class="img-fluid mb-3">
        <h3 class="h4">Jonathan Kennedy</h3>
        <p class="caption mb-3 text-primary">Founder</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam voluptas autem qui alias officia eligendi, nam in.</p>
      </div>
      <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
        <img src="{{ asset('images/person_3.jpg') }}" alt="Image" class="img-fluid mb-3">
        <h3 class="h4">Gordon Meyer</h3>
        <p class="caption mb-3 text-primary">Lead Developer</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore animi quam, est vero. Omnis sunt, totam qui!</p>
      </div>
      <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
        <img src="{{ asset('images/person_4.jpg') }}" alt="Image" class="img-fluid mb-3">
        <h3 class="h4">Doug Hale Kennedy</h3>
        <p class="caption mb-3 text-primary">ProjectManager</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae exercitationem voluptatum, laboriosam unde ipsam modi iusto, numquam?</p>
      </div>
    </div>

  </div>
</div>

@endsection

resources/views/Frontend/dashboard/checkout.blade.php
@extends('Frontend.partials.main')

@section('styles')
  <style type="text/css">
    .container {
  max-width: 960px;
}

  .border-top { border-top: 1px solid #e5e5e5; }
  .border-bottom { border-bottom: 1px solid #e5e5e5; }
  .border-top-gray { border-top-color: #adb5bd; }

  .box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05); }

  .lh-condensed { line-height: 1.25; }
  </style>
@endsection

@section('content')

   <div class="container">
      <div class="py-5 text-center">
        <h1>OfferBasket</h1>
        <h2>Checkout</h2>
        <p class="lead">Please complete all required field.</p>
      </div>

      <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">1</span>
          </h4>
          <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>

          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code">
              <div class="input-group-append">
                <button type="submit" class="btn btn-secondary">Redeem</button>
              </div>
            </div>
          </form>
        </div>
        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Billing address</h4>
          <form class="needs-validation" novalidate>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="firstName">First name</label>
                <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="lastName">Last name</label>
                <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>
            </div>

            <div class="mb-3">
              <label for="username">Username</label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">@</span>
                </div>
                <input type="text" class="form-control" id="username" placeholder="Username" required>
                <div class="invalid-feedback" style="width: 100%;">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="mb-3">
              <label for="email">Email <span class="text-muted">(Optional)</span></label>
              <input type="email" class="form-control" id="email" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="mb-3">
              <label for="address">Address</label>
              <input type="text" class="form-control" id="address" placeholder="1234 Main St" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="mb-3">
              <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
            </div>

            <div class="row">
              <div class="col-md-5 mb-3">
                <label for="country">Country</label>
                <select class="custom-select d-block w-100" id="country" required>
                  <option value="">Choose...</option>
                  <option>United States</option>
                </select>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>
              <div class="col-md-4 mb-3">
                <label for="state">State</label>
                <select class="custom-select d-block w-100" id="state" required>
                  <option value="">Choose...</option>
                  <option>California</option>
                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>
              </div>
              <div class="col-md-3 mb-3">
                <label for="zip">Zip</label>
                <input type="text" class="form-control" id="zip" placeholder="" required>
                <div class="invalid-feedback">
                  Zip code required.
                </div>
              </div>
            </div>
            <hr class="mb-4">
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="same-address">
              <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
            </div>
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="save-info">
              <label class="custom-control-label" for="save-info">Save this information for next time</label>
            </div>
            <hr class="mb-4">

            <h4 class="mb-3">Payment</h4>

            <div class="d-block my-3">
              <div class="custom-control custom-radio">
                <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
                <label class="custom-control-label" for="credit">Credit card</label>
              </div>
              <div class="custom-control custom-radio">
                <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                <label class="custom-control-label" for="debit">Debit card</label>
              </div>
              <div class="custom-control custom-radio">
                <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                <label class="custom-control-label" for="paypal">Paypal</label>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="cc-name">Name on card</label>
                <input type="text" class="form-control" id="cc-name" placeholder="" required>
                <small class="text-muted">Full name as displayed on card</small>
                <div class="invalid-feedback">
                  Name on card is required
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="cc-number">Credit card number</label>
                <input type="text" class="form-control" id="cc-number" placeholder="" required>
                <div class="invalid-feedback">
                  Credit card number is required
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3 mb-3">
                <label for="cc-expiration">Expiration</label>
                <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
                <div class="invalid-feedback">
                  Expiration date required
                </div>
              </div>
              <div class="col-md-3 mb-3">
                <label for="cc-expiration">CVV</label>
                <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
                <div class="invalid-feedback">
                  Security code required
                </div>
              </div>
            </div>
            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block mb-3" type="submit">Continue to checkout</button>
          </form>
        </div>
      </div>

@endsection

resources/views/Frontend/dashboard/pricing.blade.php
@extends('Frontend.partials.main')

@section('styles')
	<link rel="stylesheet" href="{!! asset('/css/pricing.css') !!}">
@endsection

@section('content')
<section>
  <div class='pricing pricing-palden'>
    <div class='pricing-item'>
      <div class='pricing-deco'>
        <svg class='pricing-deco-img' enable-background='new 0 0 300 100' height='100px' id='Layer_1' preserveAspectRatio='none' version='1.1' viewBox='0 0 300 100' width='300px' x='0px' xml:space='preserve' xmlns:xlink='http://www.w3.org/1999/xlink' xmlns='http://www.w3.org/2000/svg' y='0px'>
          <path class='deco-layer deco-layer--1' d='M30.913,43.944c0,0,42.911-34.464,87.51-14.191c77.31,35.14,113.304-1.952,146.638-4.729&#x000A;	c48.654-4.056,69.94,16.218,69.94,16.218v54.396H30.913V43.944z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--2' d='M-35.667,44.628c0,0,42.91-34.463,87.51-14.191c77.31,35.141,113.304-1.952,146.639-4.729&#x000A;	c48.653-4.055,69.939,16.218,69.939,16.218v54.396H-35.667V44.628z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--3' d='M43.415,98.342c0,0,48.283-68.927,109.133-68.927c65.886,0,97.983,67.914,97.983,67.914v3.716&#x000A;	H42.401L43.415,98.342z' fill='#FFFFFF' opacity='0.7'></path>
          <path class='deco-layer deco-layer--4' d='M-34.667,62.998c0,0,56-45.667,120.316-27.839C167.484,57.842,197,41.332,232.286,30.428&#x000A;	c53.07-16.399,104.047,36.903,104.047,36.903l1.333,36.667l-372-2.954L-34.667,62.998z' fill='#FFFFFF'></path>
        </svg>
        <div class='pricing-price'><span class='pricing-currency'>$</span>29
          <span class='pricing-period'>/ mo</span>
        </div>
        <h3 class='pricing-title'>Freelance</h3>
      </div>
      <ul class='pricing-feature-list'>
        <li class='pricing-feature'>10 Shops</li>
        <li class='pricing-feature'>5 Branches</li>
        <li class='pricing-feature'>500 Products</li>
      </ul>
      <a href="{{ route('checkout.checkout') }}"><button class='pricing-action'>Choose plan</button></a>
    </div>
    <div class='pricing-item pricing__item--featured'>
      <div class='pricing-deco'>
        <svg class='pricing-deco-img' enable-background='new 0 0 300 100' height='100px' id='Layer_1' preserveAspectRatio='none' version='1.1' viewBox='0 0 300 100' width='300px' x='0px' xml:space='preserve' xmlns:xlink='http://www.w3.org/1999/xlink' xmlns='http://www.w3.org/2000/svg' y='0px'>
          <path class='deco-layer deco-layer--1' d='M30.913,43.944c0,0,42.911-34.464,87.51-14.191c77.31,35.14,113.304-1.952,146.638-4.729&#x000A;	c48.654-4.056,69.94,16.218,69.94,16.218v54.396H30.913V43.944z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--2' d='M-35.667,44.628c0,0,42.91-34.463,87.51-14.191c77.31,35.141,113.304-1.952,146.639-4.729&#x000A;	c48.653-4.055,69.939,16.218,69.939,16.218v54.396H-35.667V44.628z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--3' d='M43.415,98.342c0,0,48.283-68.927,109.133-68.927c65.886,0,97.983,67.914,97.983,67.914v3.716&#x000A;	H42.401L43.415,98.342z' fill='#FFFFFF' opacity='0.7'></path>
          <path class='deco-layer deco-layer--4' d='M-34.667,62.998c0,0,56-45.667,120.316-27.839C167.484,57.842,197,41.332,232.286,30.428&#x000A;	c53.07-16.399,104.047,36.903,104.047,36.903l1.333,36.667l-372-2.954L-34.667,62.998z' fill='#FFFFFF'></path>
        </svg>
        <div class='pricing-price'><span class='pricing-currency'>$</span>59
          <span class='pricing-period'>/ mo</span>
        </div>
        <h3 class='pricing-title'>Business</h3>
      </div>
      <ul class='pricing-feature-list'>
        <li class='pricing-feature'>15 Shops</li>
        <li class='pricing-feature'>10 Branches</li>
        <li class='pricing-feature'>1000 Products</li>
      </ul>
     <a href="{{ route('checkout.checkout') }}"><button class='pricing-action'>Choose plan</button></a>
    </div>
    <div class='pricing-item'>
      <div class='pricing-deco'>
        <svg class='pricing-deco-img' enable-background='new 0 0 300 100' height='100px' id='Layer_1' preserveAspectRatio='none' version='1.1' viewBox='0 0 300 100' width='300px' x='0px' xml:space='preserve' xmlns:xlink='http://www.w3.org/1999/xlink' xmlns='http://www.w3.org/2000/svg' y='0px'>
          <path class='deco-layer deco-layer--1' d='M30.913,43.944c0,0,42.911-34.464,87.51-14.191c77.31,35.14,113.304-1.952,146.638-4.729&#x000A;	c48.654-4.056,69.94,16.218,69.94,16.218v54.396H30.913V43.944z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--2' d='M-35.667,44.628c0,0,42.91-34.463,87.51-14.191c77.31,35.141,113.304-1.952,146.639-4.729&#x000A;	c48.653-4.055,69.939,16.218,69.939,16.218v54.396H-35.667V44.628z' fill='#FFFFFF' opacity='0.6'></path>
          <path class='deco-layer deco-layer--3' d='M43.415,98.342c0,0,48.283-68.927,109.133-68.927c65.886,0,97.983,67.914,97.983,67.914v3.716&#x000A;	H42.401L43.415,98.342z' fill='#FFFFFF' opacity='0.7'></path>
          <path class='deco-layer deco-layer--4' d='M-34.667,62.998c0,0,56-45.667,120.316-27.839C167.484,57.842,197,41.332,232.286,30.428&#x000A;	c53.07-16.399,104.047,36.903,104.047,36.903l1.333,36.667l-372-2.954L-34.667,62.998z' fill='#FFFFFF'></path>
        </svg>
        <div class='pricing-price'><span class='pricing-currency'>$</span>99
          <span class='pricing-period'>/ mo</span>
        </div>
        <h3 class='pricing-title'>Enterprise</h3>
      </div>
      <ul class='pricing-feature-list'>
        <li class='pricing-feature'>15 Shops</li>
        <li class='pricing-feature'>15 Branches</li>
        <li class='pricing-feature'>2000 products</li>
      </ul>
      <a href="{{ route('checkout.checkout') }}"><button class='pricing-action'>Choose plan</button></a>
    </div>
  </div>
</section>

@endsection

@section('scripts')
	<script type="text/javascript" src="{!! asset('/js/pricing.js') !!}"></script>
@endsection